services:
  - type: web
    name: prabu-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENABLE_RATE_LIMIT
        value: "true"
      - key: RATE_LIMIT_PER_HOUR
        value: "5"
      - key: EMAIL_USER
        value: prabuarvind2005@gmail.com
      - key: EMAIL_PASSWORD
        value: dadj usli dhpm jtrh
      - key: OPENROUTER_API_KEY
        sync: false
